#!/usr/bin/env bash

labels=(activities book bookmark cloud comic development documents download favorites games gdrive html image-people important library locked mail network open pictures print publicshare root script sound tar temp templates text unlocked videos)
colors=(black blue bluegray brown cyan green grey magenta orange pink teal red violet white yellow)

if (( $# < 3 )); then
  echo Not enought arguments
  exit -1
fi

label=""
color=""

action="$1"
action_value="$2"

shift 2

for i in "$@"; do

  if [[ -f "${i}/.directory" ]]; then
    if grep -q "Icon=folder" "${i}/.directory" ; then
      iconString=$( grep "Icon=folder" "${i}/.directory" )

      for currColor in "${colors[@]}"; do
        if echo "$iconString" | grep -q -- "$currColor";then
          color="$currColor"
        fi
      done

      for currLabel in "${labels[@]}"; do
        if echo "$iconString" | grep -q -- "$currLabel";then
          label="$currLabel"
        fi
      done

    fi
  fi

  if [[ "$action" == "label" ]]; then
    label="$action_value"
  fi

  if [[ "$action" == "color" ]]; then
    color="$action_value"
  fi

  iconString="folder"

  if [[ ! -z "$color" ]]; then
    iconString+="-$color"
  fi

  if [[ ! -z "$label" ]]; then
    iconString+="-$label"
  fi

  echo $label $color $iconString
  echo "${i}/.directory"
  if [[ ! -f "${i}/.directory" ]]; then
    echo -n "" > "${i}/.directory"
    echo "[Desktop Entry]" >> "${i}/.directory"
    echo "Icon=$iconString" >> "${i}/.directory"
  else
    FILE="${i}/.directory"
    FIND=`grep -e "Icon=.*" "$FILE"`

    if [ "$FIND" != "" ]; then
      sed "s/#*Icon=.*/Icon=$iconString/g" "$FILE" > "/tmp/$$" && cat "/tmp/$$" > "$FILE"
    else
      FIND=`grep -e "\[Desktop Entry\]" "$FILE"`

      if [ "$FIND" != "" ]; then
        sed "s/#*\[Desktop Entry\]/\[Desktop Entry\]\nIcon=$iconString/g" "$FILE" > "/tmp/$$" && mv "/tmp/$$" "$FILE"
      else
        echo >> "$FILE"
        echo "[Desktop Entry]" >> "$FILE"
        echo "Icon=$iconString" >> "$FILE"
      fi
    fi
  fi
done
